name: Deploy Next.js to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🛠️ Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: 📦 Install dependencies
      run: npm install

    - name: 🏗️ Build Project
      run: npm run build

    - name: 📂 Sync files to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./out/
        server-dir: ./
        # 🚀 SERVERNI BLOKLANISHIDAN HIMOYA QILISH:
        parallel: 10 # Bir vaqtda faqat 10 ta fayl (server o'chib qolmasligi uchun)
        timeout: 120000 # 2 daqiqa
        state-name: .ftp-deploy-sync-state.json
        exclude: |
          **/.git*
          **/node_modules/**
          .next/**